/**
 * @license
 * Copyright 2025 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

import path from 'node:path';
import fs from 'node:fs';
import { GoogleGenAI } from '@google/genai';
import { makeRelative, shortenPath } from '../utils/paths.js';
import type { ToolInvocation, ToolResult } from './tools.js';
import { BaseDeclarativeTool, BaseToolInvocation, Kind } from './tools.js';
import type { Config } from '../config/config.js';
import { ToolErrorType } from './tool-error.js';
import { getErrorMessage } from '../utils/errors.js';
import { AuthType } from '../core/contentGenerator.js';

/**
 * Parameters for the DownloadFile tool
 */
export interface DownloadFileToolParams {
  /**
   * The file URI or name to download (e.g., 'files/abc123' or just the file name)
   */
  file_uri: string;

  /**
   * The absolute path where the file should be saved
   */
  download_path: string;
}

class DownloadFileToolInvocation extends BaseToolInvocation<
  DownloadFileToolParams,
  ToolResult
> {
  constructor(
    private config: Config,
    params: DownloadFileToolParams,
  ) {
    super(params);
  }

  getDescription(): string {
    const relativePath = makeRelative(
      this.params.download_path,
      this.config.getTargetDir(),
    );
    return `Downloading file to ${shortenPath(relativePath)}`;
  }

  async execute(signal: AbortSignal): Promise<ToolResult> {
    const contentGeneratorConfig = this.config.getContentGeneratorConfig();
    
    // Check if using Vertex AI - file download is not supported
    if (contentGeneratorConfig.vertexai) {
      const errorMsg = 'File download is not supported when using Vertex AI. Please use Gemini API (GEMINI_API_KEY) or OAuth authentication.';
      return {
        llmContent: errorMsg,
        returnDisplay: errorMsg,
        error: {
          message: errorMsg,
          type: ToolErrorType.DOWNLOAD_NOT_SUPPORTED,
        },
      };
    }

    try {
      // Create a GoogleGenAI instance to access the files API
      const googleGenAI = new GoogleGenAI({
        apiKey: contentGeneratorConfig.apiKey === '' ? undefined : contentGeneratorConfig.apiKey,
        vertexai: contentGeneratorConfig.vertexai,
      });

      // Download the file
      await googleGenAI.files.download({
        file: this.params.file_uri,
        downloadPath: this.params.download_path,
        config: {
          abortSignal: signal,
        },
      });

      const fileName = path.basename(this.params.download_path);
      const relativePath = makeRelative(
        this.params.download_path,
        this.config.getTargetDir(),
      );

      const successMessage = `Successfully downloaded file to: ${relativePath}
File URI: ${this.params.file_uri}
Downloaded as: ${fileName}`;

      return {
        llmContent: successMessage,
        returnDisplay: successMessage,
      };
    } catch (error) {
      const errorMessage = getErrorMessage(error);
      const errorMsg = `Error downloading file '${this.params.file_uri}' to '${this.params.download_path}': ${errorMessage}`;
      
      return {
        llmContent: errorMsg,
        returnDisplay: errorMsg,
        error: {
          message: errorMsg,
          type: ToolErrorType.FILE_DOWNLOAD_FAILURE,
        },
      };
    }
  }
}

/**
 * Implementation of the DownloadFile tool logic
 */
export class DownloadFileTool extends BaseDeclarativeTool<
  DownloadFileToolParams,
  ToolResult
> {
  static readonly Name: string = 'download_file';

  constructor(private config: Config) {
    super(
      DownloadFileTool.Name,
      'DownloadFile',
      `Downloads a file from the Gemini API file manager to the local filesystem. Use this to retrieve files that were previously uploaded or generated by the API. The file will be saved to the specified local path. Note: This tool is only available when using Gemini API authentication (not Vertex AI).`,
      Kind.Other,
      {
        properties: {
          file_uri: {
            description:
              "The URI or name of the file to download (e.g., 'files/abc123' or just the file name from the Gemini API file manager).",
            type: 'string',
          },
          download_path: {
            description:
              "The absolute path where the file should be saved (e.g., '/home/user/project/downloaded_file.mp4'). The directory must exist.",
            type: 'string',
          },
        },
        required: ['file_uri', 'download_path'],
        type: 'object',
      },
    );
  }

  protected override validateToolParamValues(
    params: DownloadFileToolParams,
  ): string | null {
    const downloadPath = params.download_path;
    
    if (params.file_uri.trim() === '') {
      return "The 'file_uri' parameter must be non-empty.";
    }

    if (params.download_path.trim() === '') {
      return "The 'download_path' parameter must be non-empty.";
    }

    if (!path.isAbsolute(downloadPath)) {
      return `Download path must be absolute, but was relative: ${downloadPath}. You must provide an absolute path.`;
    }

    const workspaceContext = this.config.getWorkspaceContext();
    const projectTempDir = this.config.storage.getProjectTempDir();
    const resolvedDownloadPath = path.resolve(downloadPath);
    const resolvedProjectTempDir = path.resolve(projectTempDir);
    const isWithinTempDir =
      resolvedDownloadPath.startsWith(resolvedProjectTempDir + path.sep) ||
      resolvedDownloadPath === resolvedProjectTempDir;

    if (!workspaceContext.isPathWithinWorkspace(downloadPath) && !isWithinTempDir) {
      const directories = workspaceContext.getDirectories();
      return `Download path must be within one of the workspace directories: ${directories.join(', ')} or within the project temp directory: ${projectTempDir}`;
    }

    // Check if parent directory exists
    const parentDir = path.dirname(downloadPath);
    try {
      if (!fs.existsSync(parentDir)) {
        return `Parent directory does not exist: ${parentDir}`;
      }
      const stats = fs.lstatSync(parentDir);
      if (!stats.isDirectory()) {
        return `Parent path is not a directory: ${parentDir}`;
      }
    } catch (_error) {
      return `Parent directory does not exist or cannot be accessed: ${parentDir}`;
    }

    // Check authentication type
    const contentGeneratorConfig = this.config.getContentGeneratorConfig();
    if (contentGeneratorConfig.vertexai) {
      return 'File download is not supported when using Vertex AI. Please use Gemini API (GEMINI_API_KEY) or OAuth authentication.';
    }

    if (
      contentGeneratorConfig.authType !== AuthType.USE_GEMINI &&
      contentGeneratorConfig.authType !== AuthType.LOGIN_WITH_GOOGLE
    ) {
      return 'File download requires either Gemini API key (GEMINI_API_KEY) or OAuth authentication.';
    }

    return null;
  }

  protected createInvocation(
    params: DownloadFileToolParams,
  ): ToolInvocation<DownloadFileToolParams, ToolResult> {
    return new DownloadFileToolInvocation(this.config, params);
  }
}
